[package]
name = "rsgl"
version = "0.1.0"
edition = "2021"
description = "A Rust library for OpenGL"
repository = "https://github.com/Anglebase/rsgl.git"
license = "MIT"

[dependencies]
ctxs = "0.1.1"
gl = "0.14.0"
glfw = "0.59.0"
